# Numpy Library:

<p><b>It's A library that have been build on top of C, for effecient scientific calculations. </b></p>

### Nd arrays:
- Multi dimensional array that hold a group of elements that forces it to have the same type.
- Much faster than plain python because it's buil on top of C
- Can have any dimensionality Unlike
- Describes Memory as follows:
    - Data Pointer: Base address or the address of the  first byte.
    - Data Type Describion: Type of the data inside the array
    - Shape: shape of array
    - Strides: Number of bytes to proceed to the nest item (rows_bytes, columns_bytes)
    - F;ags: Aloowed to edit the array or not.
    
**View of an array:**
<p> When we use an array to reference to naother array and if we change any element of any one of these we change the other one to</p>

`y = x[::2, ::2]`

<p> the difference that they are pointing to the same memory but with different strides</p>


**Usage of strides:**

-We can reshape or transpose the array with no cost of memory by changing them.


**NOTE:** The strides, shape and dtype of the array can be modified by the user.


#### 1.1  Vectorisation: 

**Grouping these element-wise operations together, allows numpy to perform a computayions rapidly using broadcasting**

#### 1.2  Broadcasting:

**Expanding the arrays so that operation becoms viable, Not physically constructed , it uses the appropraite array elements**
-  Dimensions are suitably mathed, or it will be the learger one

### Code:

In [27]:
#1. Importing Numpy:
import numpy as np

## Creting ndArrays:

In [29]:
#2. Creating and saving numpy arrays:

#2.1 create from other arryas or lists:
x= np.array([2,5,6,9])

#2.2 Using Numpy built-in function that quickly generates a numpy
zeres_array = np.zeros((3,4), dtype=np.int64)
ones_array = np.ones((4,6))
filled_by_constant = np.full((5,4), 7)
identitiy_matrix = np.eye(7)
diagonal_array = np.diag([15,20,14,19])
evenly_setp_range_array = np.arange(1,5,1) #(Start-inclusive, stop-exlusive, step-Default = 1)
evenly_nummber_of_elmetnts_in_range = np.linspace(1,100,50) #(start-inclusive, stop-inclusive, number of elements)

#2.3 Using random module:
#Between 1 exclusive and 0 inclusive
from_0_to_1_random_shaped = np.random.random((2,2))
#in a given interver
interval = np.random.randint(2,10,(1,5)) #(Start, stop-exclusive, shape)
#With statistical properties:
noremal_distribuation = np.random.normal(0,1,size=(1000,1000)) #Normal dist with mean of 0 and shape of 1000 1000 and std of 1


## Getting Information about the array:

In [30]:
#3. Useful functions to provide information about the arrays:
# 3.1 Getting the type of the array elements:
print(x.dtype)
# 3.1 Shape and dimension:
print(x.shape)
# 3.2 number of elements inside the array:
print(x.size)
#3.4 Rank of the array:
print(x.ndim)

int32
(4,)
4
1


#### Upcasting: 

when numpy upcasts one data type to another in the array to be at the smae type. (integer to float)

In [31]:
# 3.4 Specifying the data type when creting an array
y= np.array([2.3,6,4], dtype = np.int64)

In [32]:
print(y)

[2 6 4]


In [33]:
# 4 Saving array:
np.save("my_array", y)

In [34]:
# 5. Loading an array file:
z= np.load("my_array.npy")
print(z)

[2 6 4]


## Reshaping the array:

In [35]:
#Resahping an array
reshped  = np.reshape(evenly_setp_range_array, (2,2))

## Accessing Elements:

In [41]:
aa = np.arange(0,6)

In [42]:
print(aa[1], aa[-1])#postitive and negative indexing

1 5


## Modifying:

In [43]:
aa[3] = 20

In [50]:
m = aa.reshape(3,2)

In [51]:
m[1,1] = 18

In [52]:
m

array([[ 0,  1],
       [ 2, 18],
       [ 4,  5]])

## Deleting:

In [60]:
d = np.delete(m, [0], axis = 1)

In [61]:
print(d)

[[ 1]
 [18]
 [ 5]]


## Adding Values

In [65]:
ap = np.append(m, [[1, 4]], axis = 0)

In [66]:
ap

array([[ 0,  1],
       [ 2, 18],
       [ 4,  5],
       [ 1,  4]])

In [67]:
inst= np.insert(x, 1, [3,4])
inst

array([2, 3, 4, 5, 6, 9])

## Stacking:

In [70]:
#Horizontal:
h_add = [[0],[4],[5],[6]]
hstack = np.hstack((ap, h_add))

#Vertial
addd= [1,8]
vstack = np.vstack((ap, addd))

In [74]:
print(hstack, "\n", "\n" , vstack)

[[ 0  1  0]
 [ 2 18  4]
 [ 4  5  5]
 [ 1  4  6]] 
 
 [[ 0  1]
 [ 2 18]
 [ 4  5]
 [ 1  4]
 [ 1  8]]


## Slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [80]:
# 2d array: 
sl = ap[1:, 1:2] # Returning 2D array View not a copy
sl1 = ap[1:, 1] # Returning 1D Array view not a copy

In [79]:
sl

array([[18],
       [ 5],
       [ 4]])

In [81]:
sl1

array([18,  5,  4])

**Note Agian:** Slicing creating a view not a copy of the array. to creat an independat copy we use copy()method.

In [82]:
sl = sl.copy()

In [83]:
sl[1,0] = 12

In [84]:
ap

array([[ 0,  1],
       [ 2, 18],
       [ 4,  5],
       [ 1,  4]])

In [85]:
sl

array([[18],
       [12],
       [ 4]])

In [88]:
## Accessing the diagonal 
# d= np.diag([1,2,56,8])
d= np.diag(np.diag([2,5,8,9,10]))

In [89]:
d

array([ 2,  5,  8,  9, 10])

#### We can select the above and the below of the diagonal with k parameter

In [92]:
un = np.unique(d) # Sorted unique elements

In [93]:
un

array([ 2,  5,  8,  9, 10])

## Boolean indexing:

In [95]:
r = ap[(ap > 3)]

In [96]:
r

array([18,  4,  5,  4])

## Set operations in numpy array:

In [97]:
#instersectd
#uniond
#setdiff1d

## Sorting:
.sort() --> inplace "\n"
sort(array, ascending=False, axis=0or1) --> out of place